server:
  port: 8082
spring:
  application:
    name: infytel-friend-family
  cloud:
    consul:
      discovery:
        hostname: localhost
      config:
        enabled: true
        prefix: config
        defaultContext: application
        profileSeparator: '::'
        format: YAML
